# Site settings
title: Syed Waliullah's Portfolio
description: This is were I keep track of all my projects
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Syed Waliullah
user_description: Always loved to play games and thought "Hey! Why not make some?" and then the rest is history.
user_title: Game Developer
email: kamran369mars@gmail.com
twitter_username: https://twitter.com/deadlykam
github_username:  https://github.com/deadlykam

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
